export const fields = [
	{
		key: 'acquisitionType',
		label: 'Acquisition Type',
		defaultValue: '',
		displayOrder: 3,
	},
	{
		key: 'comments',
		label: 'Comments',
		defaultValue: '',
		displayOrder: 37,
	},
	{
		key: 'dateBirth',
		label: 'Date of Birth',
		defaultValue: '',
		displayOrder: 10,
	},
	{
		key: 'dateClosed',
		label: 'Date Closed',
		defaultValue: '',
		displayOrder: 18,
	},
	{
		key: 'dateEffective',
		label: 'Effective Date',
		defaultValue: '',
		displayOrder: 36,
	},
	{
		key: 'dateFilled',
		label: 'Date Filled',
		defaultValue: '',
		displayOrder: 19,
	},
	{
		key: 'dateHire',
		label: 'Hire date',
		defaultValue: '',
		displayOrder: 11,
	},
	{
		key: 'dateLeaveReturn',
		label: 'Expected Return Date',
		defaultValue: '',
		displayOrder: 34,
	},
	{
		key: 'datePosted',
		label: 'Date Posted',
		defaultValue: '',
		displayOrder: 17,
	},
	{
		key: 'dateSubmitted',
		label: 'Date Submitted',
		defaultValue: '',
		displayOrder: null,
	},
	{
		key: 'employmentType',
		label: 'Employment Type',
		defaultValue: '',
		displayOrder: 2,
	},
	{
		key: 'flsaClassification',
		label: 'FLSA Classification',
		defaultValue: '',
		displayOrder: 14,
	},
	{
		key: 'flsaClassificationNewRole',
		label: 'New Role FLSA Classification',
		defaultValue: '',
		displayOrder: 32,
	},
	{
		key: 'flsaClassificationPrevious',
		label: 'Previous FLSA Classification',
		defaultValue: '',
		displayOrder: 22,
	},
	{
		key: 'formId',
		label: 'Form ID',
		defaultValue: '',
		displayOrder: null,
	},
	{
		key: 'formName',
		label: 'Form Name',
		defaultValue: '',
		displayOrder: null,
	},
	{
		key: 'hiringLead',
		label: 'Hiring Lead',
		defaultValue: '',
		displayOrder: 8,
	},
	{
		key: 'leavePtoHours',
		label: 'PTO Hours to use after paid leave',
		defaultValue: '',
		displayOrder: 35,
	},
	{
		key: 'leaveType',
		label: 'Leave Type',
		defaultValue: '',
		displayOrder: 4,
	},
	{
		key: 'nameAssociate',
		label: 'Associate Name',
		defaultValue: '',
		displayOrder: 5,
	},
	{
		key: 'nameNewRole',
		label: 'New Role Name',
		defaultValue: '',
		displayOrder: 24,
	},
	{
		key: 'namePreviousRole',
		label: 'Previous Role Name',
		defaultValue: '',
		displayOrder: 20,
	},
	{
		key: 'newRate',
		label: 'New Rate',
		defaultValue: '',
		displayOrder: 30,
	},
	{
		key: 'notRehirable',
		label: 'Why are they not rehirable?',
		defaultValue: '',
		displayOrder: 16,
	},
	{
		key: 'numberOfDays',
		label: 'Number of Days',
		defaultValue: '',
		displayOrder: 33,
	},
	{
		key: 'otherExplanation',
		label: 'Other Explanation',
		defaultValue: '',
	},
	{
		key: 'rehireEligibility',
		label: 'Eligible for Rehire?',
		defaultValue: '',
		displayOrder: 15,
	},
	{
		key: 'requestType',
		label: 'Request Type',
		defaultValue: '',
		displayOrder: 1,
	},
	{
		key: 'role',
		label: 'Role',
		defaultValue: '',
		displayOrder: 7,
	},
	{
		key: 'salary',
		label: 'Salary',
		defaultValue: '',
		displayOrder: 9,
	},
	{
		key: 'salaryNew',
		label: 'New Salary',
		defaultValue: '',
		displayOrder: 25,
	},
	{
		key: 'salaryPrevious',
		label: 'Previous Salary',
		defaultValue: '',
		displayOrder: 21,
	},
	{
		key: 'status',
		label: 'Status',
		defaultValue: '',
		displayOrder: 13,
	},
	{
		key: 'statusNewRole',
		label: 'New Role Status',
		defaultValue: '',
		displayOrder: 31,
	},
	{
		key: 'submitterId',
		label: 'Submitter ID',
		defaultValue: '', //authUser.uid
		displayOrder: null,
	},
	{
		key: 'team',
		label: 'Team',
		defaultValue: '',
		displayOrder: 6,
	},
	{
		key: 'teamLead',
		label: 'Team Lead',
		defaultValue: '',
		displayOrder: 12,
	},
	{
		key: 'teamLeadNew',
		label: 'New Team Lead',
		defaultValue: '',
		displayOrder: 27,
	},
	{
		key: 'teamLeadPrevious',
		label: 'Previous Team Lead',
		defaultValue: '',
		displayOrder: 23,
	},
];
